use_frameworks!

platform :ios, '9.0'

target 'SRNetWorking_Example' do
  pod 'SRNetWorking', :path => '../'

  target 'SRNetWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
